require:
 - rubocop-rake
 - rubocop-rspec
 - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - spec/fixtures/somerepo/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/ClassLength:
  Max: 180
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 8
